In [1]:
which python

SyntaxError: invalid syntax (<ipython-input-1-2c530a9741f4>, line 1)

In [2]:
python?

In [3]:
import matplotlib.pyplot as plt

In [4]:
import matplotlib.ticker as mticker
import matplotlib.dates as mdates
import numpy as np

In [13]:
x = np.ones((1,2,3))
print(x)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [23]:
print(np.transpose(x, (1,0,2)))


[[[ 1.  1.  1.]]

 [[ 1.  1.  1.]]]


In [35]:
print(np.reshape(-1, 1))

[-1]


In [38]:
print(np.split(0, 1, [1, 0, 2]))

AttributeError: 'int' object has no attribute 'shape'